# Generated by Django 4.2.16 on 2024-11-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ClubAvatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Аватар Клуба'),
        ),
        migrations.AddField(
            model_name='post',
            name='ImgNews',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка Новости'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ClubName',
            field=models.CharField(max_length=50, verbose_name='Название Клуба'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='NewsName',
            field=models.CharField(max_length=50, verbose_name='Название Новости'),
        ),
    ]
