# Generated by Django 4.2.16 on 2024-11-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_clubavatar_post_imgnews_alter_post_clubname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ClubAvatar',
        ),
        migrations.AlterField(
            model_name='post',
            name='ImgNews',
            field=models.ImageField(blank=True, upload_to='main/image', verbose_name='Картинка Новости'),
        ),
    ]
